const products = [
  {
    id: "recyqtRglGNGtO4Qx",
    title: "Kirby's Dreamland (Gameboy - Excellent condition, full (euro))",
    company: "nintendo",
    image: "kirby.jpg",
    price: 69.99,
  },
  {
    id: "rec8kkCmSiMkbkiko",
    title: "REZ (Playstation 2 - Excellent condition, full (jp))",
    company: "playstation",
    image: "rez.jpg",
    price: 39.99,
  },
  {
    id: "rec43w3ipXvP28vog",
    title: "The House of The Dead (Dreamcast - mint (jp))",
    company: "sega",
    image: "house.jpg",
    price: 29.99,
  },
  {
    id: "rec8kkCmSiMkbkicu",
    title: "Top Hunter (NEOGEO - Excellent condition, full (JP))",
    company: "snk",
    image: "tophunter.jpg",
    price: 99.99,
  },
  {
    id: "rec43w3ipXvP28vog",
    title: "Metal Gear Solid (PlayStation - Excellent condition (fr))",
    company: "playstation",
    image: "mgs.jpg",
    price: 29.99,
  },
  {
    id: "rec4f2RIftFCb7aHh",
    title: "OutRun (Megadrive - Excellent condition (jp))",
    company: "sega",
    image: "outrun.jpg",
    price: 99.99,
  },
  {
    id: "recBohCqQsot4Q4II",
    title: "Super Monkey Ball 2 (Gamecube - Good condition (jp))",
    company: "nintendo",
    image: "monkey.jpg",
    price: 19.99,
  },
  {
    id: "recxaXFy5IW539sgM",
    title:
      "Mario Kart Double Dash (Gamecube - Excellent condition, full (euro))",
    company: "nintendo",
    image: "mariokart.jpg",
    price: 29.99,
  },
  {
    id: "recDG1JRZnbpRHpoy",
    title: "Panzer Dragoon Saga (Saturn - Good condition (jp))",
    company: "sega",
    image: "panzer.jpg",
    price: 6.99,
  },
  {
    id: "recNWGyP7kjFhSqw3",
    title: "Golden Axe (Megadrive - Excellent condition, full(jp))",
    company: "sega",
    image: "golden.jpg",
    price: 69.99,
  },
  {
    id: "recZEougL5bbY4AEx",
    title: "Shenmue (Dreamcast - Excellent condition, full(jp))",
    company: "sega",
    image: "shenmue.jpg",
    price: 59.99,
  },
  {
    id: "recjMK1jgTb2ld7sv",
    title: "Nights ~ Into Dreams...~ (Saturn - Excellent condition, full(jp))",
    company: "sega",
    image: "nights.jpg",
    price: 29.99,
  },
  {
    id: "recmg2a1ctaEJNZhu",
    title: "Super Mario 64 (N64 - Excellent condition, full (jp))",
    company: "nintendo",
    image: "mario64.jpg",
    price: 299.99,
  },
  {
    id: "recmg2a1ctaEJNZhu",
    title: "Streets of Rage (Megadrive - Excellent condition (euro))",
    company: "sega",
    image: "streets.jpg",
    price: 59.99,
  },
  {
    id: "recvKMNR3YFw0bEt3",
    title:
      "Yakuza 0 - Business Launch Edition (Playstation 4 -Good condition, full (jp))",
    company: "playstation",
    image: "yakuza.jpg",
    price: 39.99,
  },
  {
    id: "recyqtRglGNGtO4Qs",
    title: "Animal Crossing New Horizons (Switch - Mint (euro))",
    company: "nintendo",
    image: "animal.jpg",
    price: 39.99,
  },
  {
    id: "rec8kkCmSiMkbkibu",
    title: "Blazing Star (NEOGEO - Excellent condition, full (JP))",
    company: "snk",
    image: "blazing.jpg",
    price: 219.99,
  },
  {
    id: "recxaXFy5IW539sgM",
    title:
      "Skies of Arcadia Legends (Gamecube - Excellent condition, full (euro))",
    company: "nintendo",
    image: "skies.jpg",
    price: 19.99,
  },
  {
    id: "recyqtRglGNGtO4Q5",
    title: "Sonic The Hedgehog 2 (Megadrive - Cartridge only (jp))",
    company: "sega",
    image: "sonic.jpg",
    price: 9.99,
  },
  {
    id: "recyqtRglGNGtO4Qd",
    title: "Pokémon Aka (GameBoy - Excellent condition, full (jp))",
    company: "nintendo",
    image: "pokemon-red.jpg",
    price: 99.99,
  },
  {
    id: "recyqtRglGNGtO4Qm",
    title: "Pokémon Kin (GameBoy - Excellent condition, full (jp))",
    company: "nintendo",
    image: "pokemon-gold.jpg",
    price: 99.99,
  },
  {
    id: "recyqtRglGNGtO4Qq",
    title:
      "The Legend of Zelda, Ocarina of Time (N64, Medium condition,full (USA))",
    company: "nintendo",
    image: "ocarina.jpg",
    price: 69.99,
  },
  {
    id: "recyqtRglGNGtO4Qs",
    title: "Baten Kaitos Origins (Gamecube - Good condition, full (USA))",
    company: "nintendo",
    image: "baten.jpg",
    price: 79.99,
  },
  {
    id: "recyqtRglGNGtO4Qr",
    title: "Punch-Out!! (Famicom - Cartridge only (jp))",
    company: "nintendo",
    image: "punch.jpg",
    price: 139.99,
  },
  {
    id: "recyqtRglGNGtO4Qy",
    title: "Mario & Luigi - Superstar Saga (GBA - Good condition, full (euro))",
    company: "nintendo",
    image: "mario&luigi.jpg",
    price: 109.99,
  },
  {
    id: "recyqtRglGNGtO4Qx",
    title: "Pikmin (Gamecube - Excellent condition, full (euro))",
    company: "nintendo",
    image: "pikmin.jpg",
    price: 39.99,
  },
  {
    id: "recyqtRglGNGtO4Qx",
    title: "Shinobi III (Megadrive - Excellent condition, full (euro))",
    company: "sega",
    image: "shinobi.jpg",
    price: 89.99,
  },
  {
    id: "recyqtRglGNGtO4Qx",
    title: "F-Zero GX (Gamecube - Excellent condition, full (jp))",
    company: "nintendo",
    image: "fzero.jpg",
    price: 19.99,
  },
  {
    id: "rec8kkCmSiMkbkicu",
    title: "Andro Dunos (NEOGEO - Excellent condition, full (JP))",
    company: "snk",
    image: "andro.jpg",
    price: 199.99,
  },
];
